### ISSUE TITLE
Can we include this in web apps?

### ISSUE THREAD

**Issue by jefffriesen** [jhugman/turo-app#1]
It would be cool to be able to embed in a javascript web app. For example, an awesome notepad for engineering tools and data collection field tools. We probably would use it in our app.

Is this possible right now? I see in your `package.json` that you have `"turo": "jhugman/turo",` as a dependency, which I think is a private repo. 

I did read you want to open-source it here: https://github.com/jhugman/turo-docs but not sure if that is still the case.

Thank you for considering it.

**Comment by jhugman** [comment]
I'm fairly sure we have some thing interesting here, with a bunch of 
opportunities in there somewhere.

We'd like to see if we can build some value around the editor before 
open sourcing it. That is to say: we want to open source it, but would 
like to explore those opportunities which may be incompatible with 
immediate open sourcing of the most interesting bits of the codebase.

That's not to say this conversation needs to end right now: my email is 
james@turo.io .

**Comment by jefffriesen** [comment]
Got it. I'm watching this repo so I'll keep an eye on it. We're in the middle of evaluating some things with our software. I'll email you if I have specific questions. 

Thanks!
